apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: server
          image: grcp/gateway
          imagePullPolicy: Never
          ports:
            - containerPort: 50000
          env:
            - name: BACKEND_PORT
              value: "backend:50001"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: grpc
      port: 50000
      targetPort: 50000